package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func main() {
	semver := flag.Bool("semver", false, "strip leading v from version output")
	dirty := flag.Bool("dirty", false, "include +dirty when available")
	flag.Parse()

	root, err := findGoModRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	versionDir := filepath.Join(root, ".version")
	mainPath := filepath.Join(versionDir, "main.go")
	if err := ensureVersionMain(mainPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer cleanupVersionMain(versionDir, mainPath)

	if err := runVersionMain(root, *semver, *dirty); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

const versionMarker = "// Code generated by pkt.systems/version/println; DO NOT EDIT."

func findGoModRoot() (string, error) {
	start, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("read working directory: %w", err)
	}
	dir := start
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", start)
		}
		dir = parent
	}
}

func ensureVersionMain(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create .version directory: %w", err)
	}
	existing, err := os.ReadFile(path)
	if err == nil {
		if !bytes.HasPrefix(existing, []byte(versionMarker)) {
			return fmt.Errorf("%s exists but is not managed by pkt.systems/version/println", path)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", path, err)
	}
	return os.WriteFile(path, []byte(versionMainTemplate()), 0o644)
}

func runVersionMain(root string, semver bool, dirty bool) error {
	args := []string{"run", "./.version"}
	if semver {
		args = append(args, "-semver")
	}
	if dirty {
		args = append(args, "-dirty")
	}
	cmd := exec.Command("go", args...)
	cmd.Dir = root
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run()
}

func cleanupVersionMain(dir string, path string) {
	data, err := os.ReadFile(path)
	if err == nil && bytes.HasPrefix(data, []byte(versionMarker)) {
		_ = os.Remove(path)
	}
	_ = os.Remove(dir)
}

func versionMainTemplate() string {
	var b strings.Builder
	b.WriteString(versionMarker)
	b.WriteString("\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"flag\"\n")
	b.WriteString("\t\"fmt\"\n\n")
	b.WriteString("\t\"pkt.systems/version\"\n")
	b.WriteString(")\n\n")
	b.WriteString("func main() {\n")
	b.WriteString("\tsemver := flag.Bool(\"semver\", false, \"strip leading v from version output\")\n")
	b.WriteString("\tdirty := flag.Bool(\"dirty\", false, \"include +dirty when available\")\n")
	b.WriteString("\tflag.Parse()\n\n")
	b.WriteString("\tvar value string\n")
	b.WriteString("\tswitch {\n")
	b.WriteString("\tcase *semver && *dirty:\n")
	b.WriteString("\t\tvalue = version.CurrentSemverWithDirty()\n")
	b.WriteString("\tcase *semver:\n")
	b.WriteString("\t\tvalue = version.CurrentSemver()\n")
	b.WriteString("\tcase *dirty:\n")
	b.WriteString("\t\tvalue = version.CurrentWithDirty()\n")
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\tvalue = version.Current()\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tfmt.Println(value)\n")
	b.WriteString("}\n")
	return b.String()
}
